POST http://127.0.0.1:8000/api/cells/
Content-Type: application/json

{
    "label": "cash",
    "title": "Test",
    "amount": "283,748",
    "frequency": "One Time",
    "priority": "Low Priority"
}