# Generated by Django 3.0.4 on 2020-04-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
                ('frequency', models.CharField(max_length=25)),
                ('priority', models.CharField(max_length=25)),
            ],
        ),
    ]
