export const days = new Object();
days["Sun"] = "Sunday";
days["Mon"] = "Monday";
days["Tue"] = "Tuesday";
days["Wed"] = "Wednesday";
days["Thu"] = "Thursday";
days["Fri"] = "Friday";
days["Sat"] = "Saturday";
days["Sun"] = "Sunday";
